# Generated by Django 5.1.15 on 2026-07-23 11:42

import billing.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Квартира')),
                ('electricity_meter_type', models.CharField(choices=[('single', 'Однотарифный'), ('dual', 'День/Ночь')], default='single', max_length=10, verbose_name='Тип счётчика электроэнергии')),
                ('has_cold_water', models.BooleanField(default=True, verbose_name='Холодная вода')),
                ('has_hot_water', models.BooleanField(default=True, verbose_name='Горячая вода')),
                ('has_sewage', models.BooleanField(default=True, verbose_name='Водоотведение')),
                ('rent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Аренда')),
                ('internet', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Интернет')),
                ('other_fixed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Прочее')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('cold_water', 'Холодная вода'), ('hot_water', 'Горячая вода'), ('sewage', 'Водоотведение'), ('electricity_single', 'Электроэнергия'), ('electricity_day', 'Электроэнергия (день)'), ('electricity_night', 'Электроэнергия (ночь)')], max_length=32, verbose_name='Услуга')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Тариф, ₽/ед.')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('source_url', models.URLField(blank=True, verbose_name='Ссылка на источник')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['utility_type', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('messenger_platform', models.CharField(blank=True, max_length=10)),
                ('messenger_chat_id', models.CharField(blank=True, max_length=64)),
                ('link_code', models.CharField(blank=True, max_length=32)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='billing.apartment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жилец',
                'verbose_name_plural': 'Жильцы',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=billing.models.document_upload_path, verbose_name='Файл')),
                ('title', models.CharField(default='Договор аренды', max_length=200, verbose_name='Название')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='billing.tenant')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('meter', models.CharField(max_length=32, verbose_name='Счётчик')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Показание')),
                ('entered_by_tenant', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='billing.apartment')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'ordering': ['-period', 'meter'],
                'unique_together': {('apartment', 'period', 'meter')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('lines', models.JSONField(default=list, verbose_name='Строки начисления')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Итого')),
                ('status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('pending', 'На проверке'), ('paid', 'Оплачено')], default='unpaid', max_length=10, verbose_name='Статус')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='billing.apartment')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
                'ordering': ['-period'],
                'unique_together': {('apartment', 'period')},
            },
        ),
    ]
