# Generated by Django 5.1.15 on 2026-07-24 08:48

import billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=billing.models.receipt_upload_path, verbose_name='Чек')),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX'), ('web', 'Веб')], max_length=10, verbose_name='Источник')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.monthlystatement')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
