# Generated by Django 5.1.15 on 2026-07-24 13:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='gvs_heat_norm',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='Тепло на подогрев 1 м³ горячей воды — см. квитанцию УК (обычно 0,05–0,065 Гкал/м³).', max_digits=7, verbose_name='Норматив подогрева ГВС, Гкал/м³'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='utility_type',
            field=models.CharField(choices=[('cold_water', 'Холодная вода'), ('hot_water_cold_component', 'ГВС — компонент на холодную воду'), ('hot_water_heat_component', 'ГВС — компонент на тепловую энергию'), ('sewage', 'Водоотведение'), ('electricity_single', 'Электроэнергия'), ('electricity_day', 'Электроэнергия (день)'), ('electricity_night', 'Электроэнергия (ночь)')], max_length=32, verbose_name='Услуга'),
        ),
    ]
