# Generated by Django 5.1.15 on 2026-07-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_apartment_gvs_heat_norm_alter_tariff_utility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='meter',
            field=models.CharField(choices=[('cold_water', 'Холодная вода'), ('hot_water', 'Горячая вода'), ('electricity_single', 'Электроэнергия'), ('electricity_day', 'Электроэнергия (день)'), ('electricity_night', 'Электроэнергия (ночь)')], max_length=32, verbose_name='Счётчик'),
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cold_water', 'Холодная вода'), ('hot_water', 'Горячая вода'), ('electricity_single', 'Электроэнергия'), ('electricity_day', 'Электроэнергия (день)'), ('electricity_night', 'Электроэнергия (ночь)')], max_length=32, verbose_name='Вид')),
                ('serial_number', models.CharField(blank=True, max_length=64, verbose_name='Заводской номер')),
                ('initial_value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Начальное показание')),
                ('initial_date', models.DateField(blank=True, help_text='Дата акта / подписания договора.', null=True, verbose_name='Дата фиксации')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='billing.apartment')),
            ],
            options={
                'verbose_name': 'Счётчик',
                'verbose_name_plural': 'Счётчики',
                'unique_together': {('apartment', 'kind')},
            },
        ),
    ]
