# Generated by Django 5.1.15 on 2026-07-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_meterreading_meter_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='round_total',
            field=models.BooleanField(default=True, help_text='Итог свыше 10 000 ₽ округляется вниз до кратного 50 ₽ (строка «Округление» в квитанции).', verbose_name='Округлять итог'),
        ),
    ]
