# Generated by Django 5.1.15 on 2026-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_apartment_round_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Согласие на обработку ПДн дано'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='privacy_consent_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='Версия политики на момент согласия'),
        ),
    ]
