"""Шаг C3a: объект выводят из эксплуатации, а не удаляют.

Колонка появляется пустой: все заведённые объекты действуют. Обратная
миграция её удаляет — сведения о выводе теряются, но самой операции до этого
шага не существовало, и терять нечему.

Почему удаление исчезает как операция, а не остаётся для пустых объектов —
`billing/models.py`, `PropertyNotDeletable`.
"""

# Generated by Django 5.1.15 on 2026-08-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_meters_move_to_metering_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='decommissioned_on',
            field=models.DateField(blank=True, help_text='Пусто — объект в эксплуатации.', null=True, verbose_name='Выведен из эксплуатации'),
        ),
    ]
