"""Шаг C3d: число тарифных зон исчезает из карточки объекта.

[ADR-0028](../../../../docs/architecture/adr/0028-electricity-zones-are-derived-from-the-registry.md)
уточняет [ADR-0006](../../../../docs/architecture/adr/0006-electricity-meter-zones-ownership.md):
поле не переносится в Metering, а удаляется. С шага C2e состав начисляемого
задаёт реестр приборов, и «однотарифный или день/ночь» стало вторым голосом,
утверждающим то же самое, — ровно та болезнь, которую C2e и вылечил.

Значения не мигрируют никуда: они не несут сведений, которых не было бы в
реестре. Обратная миграция вернёт колонку со значением по умолчанию
«однотарифный» — для квартир с зонными приборами это будет неправдой, но
неправдой ничего не решающей: расчёт по этому полю не идёт с шага C2e.
"""

# Generated by Django 5.1.15 on 2026-08-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_speak_the_module_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='electricity_meter_type',
        ),
    ]
