"""Шаг C3e: у объекта появляется адрес.

Его не было вовсе — а отчёту бухгалтеру он нужен: наименование «студия у
метро» в документ не поставишь. Колонка заводится пустой и необязательной: у
владельца двух квартир адрес в голове, и требовать его при заведении объекта
значит мешать ради формальности.
"""

# Generated by Django 5.1.15 on 2026-08-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_electricity_zones_come_from_the_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, help_text='Одной строкой, как в документах: город, улица, дом, квартира. Печатается в отчётах.', max_length=500, verbose_name='Адрес'),
        ),
    ]
