# Generated by Django 5.1.15 on 2026-08-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.PositiveIntegerField(db_index=True, verbose_name='Учётная запись')),
                ('policy_version', models.CharField(max_length=32, verbose_name='Редакция политики')),
                ('given_at', models.DateTimeField(verbose_name='Дано')),
            ],
            options={
                'verbose_name': 'Согласие на обработку ПДн',
                'verbose_name_plural': 'Согласия на обработку ПДн',
                'db_table': 'identity_consent',
                'ordering': ['given_at'],
            },
        ),
    ]
