"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.environ.get("SECRET_KEY", "dev-insecure-key-change-me")
DEBUG = os.environ.get("DEBUG", "1") == "1"
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Fail closed: a production process (DEBUG=0) must never silently run with the
# dev secret key — that means the .env file is missing or incomplete.
if not DEBUG:
    if SECRET_KEY == "dev-insecure-key-change-me":
        raise ImproperlyConfigured(
            "DEBUG=0 but SECRET_KEY is the dev default — set SECRET_KEY in .env")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "crispy_forms",
    "crispy_tailwind",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.yandex",
    "allauth.socialaccount.providers.vk",
    "billing",
    "billing.esia_provider",
    # Шина событий (ADR-0027). Приложение — только ради журнала публикаций
    # (шаг B2); транспорту база не нужна.
    "bus",
    # Модули целевой архитектуры. Первый — Tariffs (шаг C1): лист графа,
    # у которого нет ни одного FK и на который никто не ссылается.
    "modules.tariffs.apps.TariffsConfig",
    "modules.metering.apps.MeteringConfig",
    "modules.properties.apps.PropertiesConfig",
    "modules.identity.apps.IdentityConfig",
]

SITE_ID = 1

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DB_ENGINE selects the adapter: "sqlite" (default — the MVP runs SQLite even
# in production; the VPS is 1 CPU / 1 GB) or "postgres" (set the DB_* vars and
# install the postgres extra: uv sync --extra postgres).
DB_ENGINE = os.environ.get("DB_ENGINE", "sqlite")
if DB_ENGINE == "postgres":
    DATABASES = {"default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["DB_NAME"],
        "USER": os.environ.get("DB_USER", ""),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }}
elif DB_ENGINE == "sqlite":
    DATABASES = {"default": {
        "ENGINE": "django.db.backends.sqlite3",
        # In Docker this points into the persistent volume (/data/db.sqlite3).
        "NAME": os.environ.get("SQLITE_PATH", BASE_DIR / "db.sqlite3"),
        "OPTIONS": {
            # WAL lets gunicorn workers read while one writes; IMMEDIATE
            # transactions + busy_timeout avoid "database is locked" errors.
            "init_command": (
                "PRAGMA journal_mode=WAL;"
                "PRAGMA synchronous=NORMAL;"
                "PRAGMA busy_timeout=5000;"
            ),
            "transaction_mode": "IMMEDIATE",
        },
    }}
else:
    raise ImproperlyConfigured(f"Unknown DB_ENGINE: {DB_ENGINE!r} (sqlite|postgres)")


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ru"
TIME_ZONE = "Asia/Yekaterinburg"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}
MEDIA_URL = "media/"
# In Docker this points into the persistent volume (/data/media).
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", BASE_DIR / "media"))

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "current_month"
LOGOUT_REDIRECT_URL = "login"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Миграции модулей лежат в `infrastructure/`, а не в `<приложение>/migrations/`,
# куда Django смотрит по умолчанию. Причина — правило 3.2: миграция описывает
# схему, то есть это инфраструктура и есть, и класть её на уровень пакета
# значило бы вынести ORM за пределы единственного слоя, которому она разрешена.
MIGRATION_MODULES = {
    "tariffs": "modules.tariffs.infrastructure.migrations",
    "metering": "modules.metering.infrastructure.migrations",
    "properties": "modules.properties.infrastructure.migrations",
    "identity": "modules.identity.infrastructure.migrations",
}


# Reverse proxy / production (Caddy terminates TLS and proxies over plain HTTP)
# https://docs.djangoproject.com/en/5.1/ref/settings/#secure-proxy-ssl-header

# Caddy's reverse_proxy sets X-Forwarded-Proto; trust it so Django knows the
# original request was HTTPS (correct scheme in redirects, secure cookies, etc.).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Origins (scheme required) allowed for CSRF-protected POSTs. Django 5 rejects
# HTTPS form posts whose Origin isn't listed here. e.g.
#   CSRF_TRUSTED_ORIGINS=https://domiq-ufa.ru
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Send warnings/errors (incl. unhandled-500 tracebacks) to stderr regardless of
# DEBUG, so they land in journald under gunicorn. Django's default config mails
# them to ADMINS (unconfigured) and silences the console when DEBUG=0.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "{levelname} {asctime} {name} {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}

# Harden cookies and transport only in production (DEBUG=0). Left off in dev so
# the http://localhost login still works.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Messenger bot (Plan 2)
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_WEBHOOK_SECRET = os.environ.get("TELEGRAM_WEBHOOK_SECRET", "")

# OAuth login (Yandex ID / VK ID / Gosuslugi) — additive to password login.
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SOCIALACCOUNT_ADAPTER = "billing.adapters.NoSignupSocialAccountAdapter"
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_LOGIN_ON_GET = True

# OAuth providers. Client credentials come from each provider's own app
# registration console; test values are fine for local dev (the redirect
# still 302s toward the real provider — only completing a real login
# requires real, registered credentials).
SOCIALACCOUNT_PROVIDERS = {
    "yandex": {
        "APP": {
            "client_id": os.environ.get("YANDEX_CLIENT_ID", ""),
            "secret": os.environ.get("YANDEX_CLIENT_SECRET", ""),
        },
    },
    "vk": {
        "APP": {
            "client_id": os.environ.get("VK_CLIENT_ID", ""),
            "secret": os.environ.get("VK_CLIENT_SECRET", ""),
        },
    },
    "esia": {
        "APP": {
            "client_id": os.environ.get("ESIA_CLIENT_ID", ""),
            "secret": os.environ.get("ESIA_CLIENT_SECRET", ""),
        },
        # Deliberately minimal: broader ESIA scopes (full name, SNILS, email)
        # require every authorization request to carry a PKCS#7 signature
        # made with a GOST-2012-256 certificate registered with the
        # ministry. "openid" alone (just a stable person identifier) avoids
        # that requirement entirely — see the design spec.
        "SCOPE": ["openid"],
    },
}

# Госуслуги (ESIA) sandbox by default — fail obviously rather than talking
# to production ESIA from a misconfigured deployment. Switch to
# https://esia.gosuslugi.ru once accredited with real production credentials.
ESIA_BASE_URL = os.environ.get("ESIA_BASE_URL", "https://esia-portal1.test.gosuslugi.ru")
ESIA_ALLOW_UNVERIFIED_SIGNATURE = os.environ.get("ESIA_ALLOW_UNVERIFIED_SIGNATURE", "0") == "1"

# billing/esia_provider decodes the ESIA id_token WITHOUT verifying its
# cryptographic signature (no verification certificate until real ESIA
# accreditation). Refuse to boot against production Gosuslugi with that gap
# open unless the deployer has explicitly acknowledged the risk.
if not DEBUG and "esia-portal1.test" not in ESIA_BASE_URL and not ESIA_ALLOW_UNVERIFIED_SIGNATURE:
    raise ImproperlyConfigured(
        "ESIA_BASE_URL points at production Gosuslugi but id_token signature "
        "verification is not implemented (see billing/esia_provider/views.py). "
        "Set ESIA_ALLOW_UNVERIFIED_SIGNATURE=1 only after you have reviewed "
        "and accepted this risk, or keep ESIA_BASE_URL pointed at the sandbox."
    )
