"""Шаг C2g: замок периода — собственное понятие Metering.

[ADR-0012](../../../../docs/architecture/adr/0012-metering-period-lock.md):
замок ставит Billing в момент выставления счёта, хранит и применяет Metering,
снимает владелец. Обратное — чтобы Metering спрашивал Billing — замкнуло бы
цикл: обращение Billing → Metering уже занято ради потребления.

Таблица заводится пустой и такой остаётся до шага E4: закрывать периоды
сегодня некому, а сам по себе замок ничего не меняет.
"""

# Generated by Django 5.1.15 on 2026-08-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0002_speak_the_module_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_id', models.PositiveIntegerField(db_index=True, verbose_name='Квартира')),
                ('period', models.DateField(verbose_name='Период')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Закрыт')),
            ],
            options={
                'verbose_name': 'Закрытый период',
                'verbose_name_plural': 'Закрытые периоды',
                'db_table': 'metering_period_lock',
                'ordering': ['-period'],
                'unique_together': {('apartment_id', 'period')},
            },
        ),
    ]
